name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build
        run: |
          npm install
          npm run build
      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: ".vitepress/dist/*"
          target: "~/deploy_temp"
          rm: true
          strip_components: 1
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo rm -rf ${{ secrets.SERVER_DEPLOY_PATH }}/*
            sudo cp -r ~/deploy_temp/* ${{ secrets.SERVER_DEPLOY_PATH }}/
            rm -rf ~/deploy_temp